### ISSUE TITLE
 use fetch instead of jquery ajax

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-resource-loader#1]
https://developer.telerik.com/featured/fetch-modern-async-server-calls/
with an optional polyfill for older browsers: https://github.com/github/fetch

when we get rid of jQuery dependency in the condLoader we can use it in more projects and jQuery can be a dependecy we load with the conditional loader - much more flexibility.

lets have a look at https://github.com/jhabdas/fetch-inject especially for performance

**Comment by janrembold** [comment]
+1 for vanilla

I would also like to take it one step further and rewrite it to TypeScript and ES6

**Comment by SheepFromHeaven** [comment]
solved by #15
