### ISSUE TITLE
Add script for making data-init backward compatible 

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-resource-loader#172]
As a developer I want migration from v1 or v2 to v3 as easy as possible. This includes also that I get the script that makes data-init backward compatible either in the docs or as a script I can import.

**Comment by timomayer** [comment]
@ctmm any news on this

**Comment by ctmm** [comment]
I tested this on one of our internal projects and it's simple to migrate. 

However, it seems there is a racing condition which is causing trouble. I haven't found the source yet.

I'd say it's 50% done.
I would feel safer if it's tested on needs on some other projects before I open a PR.

Any suggestion?
