### ISSUE TITLE
initialization feature backward compatability with none class based js files

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-resource-loader#176]
As discussed in this comment:
https://github.com/biotope/biotope-resource-loader/pull/168#discussion_r428313151

i am pretty sure projects using loader v1 and v2 are using a lot js files which are neither class based nor self initializing. make loader v3 compatible with them is a must otherwise we ll see very slow adoption of loader v3

**Comment by ctmm** [comment]
Closing as any javascript resource is compatible with the `scriptReadyEvent` event.
