### ISSUE TITLE
events when data is loaded and initialized

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-resource-loader#5]
the conditional loader should fire events when
all resources for a data-resource attr are loaded on the same DOM element
when data-init is executed on the same DOM element

when all resources in the page are loaded on the $(document)
when all things are initialized (with the main.js) on the $(document)

**Comment by SheepFromHeaven** [comment]
@timomayer 
- [ ] when all resources for a data-resource attr are loaded on the same DOM element
OKAY

- [ ] when data-init is executed on the same DOM element 
as data init and conditional resource loader are 2 different concepts, I would not mix the intents

- [ ] when all resources in the page are loaded on the $(document)
OKAY

- [ ] when all things are initialized (with the main.js) on the $(document)
again, main.js is not directly connected to the resource loader, so no mixing here

what's your opinion to that?

**Comment by timomayer** [comment]
you are right @SheepFromHeaven thanks & go. but please keep issue #10 in mind when you implement this one.
